### ISSUE TITLE
Save authoring info on articles / blog

### ISSUE THREAD

**Issue by wioux** [EFForg/trainers-hub#70]

**Comment by vbrown608** [comment]
Do you mean add an author field, or remember which logged-in user authored the content for internal bookkeeping? If the latter, we might be able to do it using the same gem we use for revision history.

**Comment by wioux** [comment]
Add an author field -- the new mockup includes bylines for blog posts and articles. It would be "saving" for blog posts I guess since the author name should be present in the RSS info.
